package com.example.demo.controller;


import com.example.demo.models.User;
import com.example.demo.repositories.userRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class UserController {

    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private userRepository userRepository;

    @GetMapping("/addUser")
    public String addForm(Model model) {
        System.out.println("add getter reached");
        model.addAttribute("user", new User());
        return "userAdder";
    }

    @PostMapping("/addUser")
    public ModelAndView addSubmit(@ModelAttribute User user) {
        userRepository.save(user);
        System.out.println("add setter reached");
        return new ModelAndView("redirect:/allUsers");
    }

    @GetMapping(path="/allUsers")
    public String getAllBooks(Model model) {
        model.addAttribute("users", userRepository.findAll());
        return "userLister";
    }

}
